services:
  omeka-s-db-1:
    image: mariadb:latest
    container_name: omeka-s-db-1
    ports:
      - "3306:3306"
    volumes:
      - omeka-s-db-1:/var/lib/mysql
    environment:
      MARIADB_DATABASE: $MYSQL_DATABASE
      MARIADB_USER: $MYSQL_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD
    secrets:
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    networks:
      - omeka-s-network-1
    restart: unless-stopped
  omeka-s-pma-1:
    image: phpmyadmin/phpmyadmin:latest
    container_name: omeka-s-pma-1
    ports:
      - "8080:80"
    environment:
      PMA_HOST: omeka-s-db-1
      UPLOAD_LIMIT : 512M
    networks:
      - omeka-s-network-1
    restart: unless-stopped
    depends_on:
      - omeka-s-db-1
  omeka-s-app-1:
    build:
      context: omeka-s
      dockerfile: Dockerfile
      args:
        - OMEKA_S_VERSION=$OMEKA_S_VERSION
    image: gws/omeka-s
    container_name: omeka-s-app-1
    ports:
      - "8000:80"
    volumes:
      - omeka-s-1:/var/www/html
    environment:
      DB_NAME: $MYSQL_DATABASE
      DB_USER: $MYSQL_USER
      DB_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      DB_HOST: omeka-s-db-1
      DB_PORT: 3306
    secrets:
      - MYSQL_PASSWORD
    networks:
      - omeka-s-network-1
    restart: unless-stopped
    depends_on:
      - omeka-s-db-1
volumes:
  omeka-s-db-1:
  omeka-s-1:
networks:
  omeka-s-network-1:
    driver: bridge
secrets:
  MYSQL_PASSWORD:
    file: ./secrets/MYSQL_PASSWORD.txt
  MYSQL_ROOT_PASSWORD:
    file: ./secrets/MYSQL_ROOT_PASSWORD.txt