services:
  omeka-s-db:
    image: mariadb:latest
    volumes:
      - omeka-s-db:/var/lib/mysql
    environment:
      MARIADB_DATABASE: $DB_NAME
      MARIADB_USER: $DB_USERNAME
      MARIADB_PASSWORD: $DB_PASSWORD
      MARIADB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    networks:
      - omeka-s-network
    restart: unless-stopped
  omeka-s-pma:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: omeka-s-db
      UPLOAD_LIMIT : 512M
    networks:
      - omeka-s-network
    restart: unless-stopped
    depends_on:
      - omeka-s-db
  omeka-s-app:
    build:
      context: omeka-s
      dockerfile: Dockerfile
      args:
        - OMEKA_S_VERSION=$OMEKA_S_VERSION
    image: gws/omeka-s
    ports:
      - "8000:80"
    volumes:
      - omeka-s:/var/www/html
    environment:
      DB_NAME: $DB_NAME
      DB_USER: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: omeka-s-db
      DB_PORT: 3306
    networks:
      - omeka-s-network
    restart: unless-stopped
    depends_on:
      - omeka-s-db
volumes:
  omeka-s-db:
  omeka-s:
networks:
  omeka-s-network:
    driver: bridge
    name: "${COMPOSE_PROJECT_NAME}-omeka-s-network"